name : build and test

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04]
        libclang-version: ["6.0","7","8","9","10","11","12"]
        cxx-std: ['c++03', 'c++11', 'c++14', 'c++17', 'c++2a']
        optim-level: ['-O3']
    runs-on: ${{ matrix.runs-on }}
    env:
      CXX: clang++-${{ matrix.libclang-version }}
      CXXFLAGS: -std=${{ matrix.cxx-std }} ${{ matrix.optim-level }} -Wall -Wextra 
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      if: startsWith(matrix.runs-on, 'ubuntu')
      run: |
        sudo apt update -qq 
        DEBIAN_FRONTEND="noninteractive" sudo apt install -y lsb-release software-properties-common wget
        wget - https://apt.llvm.org/llvm.sh -o llvm.sh
        sudo bash llvm.sh 12

        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list       

        sudo apt update -qq 
        sudo apt install -y rapidjson-dev build-essential -y clang-${{ matrix.libclang-version }} libclang-${{ matrix.libclang-version }}-dev libclang-12-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=${CXX} ..
        make -j`nproc`
