name : build and test

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04]
        libclang-version: ["6.0","7","8","9","10","11"]
        cxx-std: ['c++03', 'c++11', 'c++14', 'c++17', 'c++2a']
        optim-level: ['-O3']
    runs-on: ${{ matrix.runs-on }}
    env:
      CXX: clang++-${{ matrix.libclang-version }}
      CXXFLAGS: -std=${{ matrix.cxx-std }} ${{ matrix.optim-level }} -Wall -Wextra 
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      if: startsWith(matrix.runs-on, 'ubuntu')
      run: |
        sudo apt update -qq 
        DEBIAN_FRONTEND="noninteractive" sudo apt install -y lsb-release software-properties-common wget
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

        sudo cat << EOF >> /etc/apt/sources.list.d/llvm.list
        deb http://apt.llvm.org/focal/ llvm-toolchain-focal main
        deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main
        # 11
        deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main
        deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main
        # 12
        deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
        deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
        EOF

        sudo apt update -qq 
        sudo apt install -y rapidjson-dev build-essential -y clang-${{ matrix.libclang-version }} libclang-${{ matrix.libclang-version }}-dev libclang-11-dev libclang-12-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=${CXX} ..
        make -j`nproc`
