name: "pre-release"

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          sudo apt update 
          DEBIAN_FRONTEND="noninteractive" sudo apt install -y lsb-release software-properties-common curl
          curl -sLf https://apt.llvm.org/llvm.sh -o llvm.sh
          DEBIAN_FRONTEND="noninteractive" sudo bash llvm.sh 12
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list       

          sudo apt update 
          DEBIAN_FRONTEND="noninteractive" sudo apt install -y rapidjson-dev build-essential -y clang-12 libclang-12-dev libclang-10-dev
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ ..
          cpack

      - uses: "marvinpinto/action-automatic-releases@latest"
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            build/*.deb
